project:
  name: quickstart-ibm-spectrum-scale
  owner: dhersing@in.ibm.com
  package_lambda: false
  shorten_stack_name: true
  regions:
  - ap-northeast-1
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  quickstart-ibm-spectrum-scalet1:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      KeyPairName: $[taskcat_getkeypair]
      LicenseAgreementTerms: Accept
      OperatorEmail: quickstart@example.com
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 10.0.0.0/16
    regions:
      - ap-northeast-1
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    s3_bucket: ''
    template: templates/ibm-spectrum-scale-master.template
